services:
    db:
        image: postgres:latest
        container_name: veggie_tales_db
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
